/**
 * CaptureStore — the persistence layer. Every screenshot-producing tool saves
 * its full-resolution render under .agent-eyes/captures/run-<n>-<page>/ before
 * returning. A run groups one tool turn (e.g. the four matrix shots) or a chain
 * of consecutive interactions; each run keeps a manifest.json that feeds the
 * .agent-eyes/gallery.html contact sheet. File writes go through write-then-
 * rename so a crash never leaves corrupt files, and an auto-generated
 * .agent-eyes/.gitignore keeps the heavy captures out of the user's repository.
 */

import { mkdir, readFile, rename, writeFile } from "node:fs/promises";
import path from "node:path";

import type { Page } from "playwright-core";

import { MATRIX_FORMAT, MATRIX_QUALITY, type EncodedImage } from "../types/images.js";
import type { LayoutScan } from "../types/layout.js";
import {
  AGENT_EYES_DIR,
  CAPTURES_DIRNAME,
  GALLERY_FILENAME,
  RUN_MANIFEST_FILENAME,
  SCREENSHOT_BASENAME,
  type PersistingTool,
  type RunInfo,
  type SavedShot,
} from "../types/persistence.js";
import type { ViewportName } from "../types/viewports.js";
import { paintIssueOverlay } from "../inpage/overlay.js";
import type { Encoder } from "./encoder.js";
import { messageOf } from "./errors.js";
import {
  readAllShots,
  readManifest,
  renderGalleryHtml,
  type GalleryShot,
} from "./gallery.js";
import { collectIssueSelectors, countLayoutIssues } from "./layout-scan.js";
import {
  extensionOf,
  nextRunNumber,
  pageSlugFromUrl,
  pathExists,
  shotLabel,
  writeShotInfo,
} from "./paths.js";
import { rawScreenshot } from "./screenshot.js";

/** A run directory plus the filenames already used inside it. */
interface RunHandle extends RunInfo {
  usedNames: Set<string>;
  /** Count of shots saved so far this run; drives the per-shot NN prefix. */
  count: number;
}

export class CaptureStore {
  /** The run that consecutive interactions keep appending to. */
  private currentRun: RunHandle | null = null;
  private gitignoreEnsured = false;

  private agentEyesRoot(): string {
    return path.resolve(process.cwd(), AGENT_EYES_DIR);
  }

  private capturesRootDir(): string {
    return path.join(this.agentEyesRoot(), CAPTURES_DIRNAME);
  }

  /** The .agent-eyes/captures directory (used by generate_audit_gallery). */
  capturesRoot(): string {
    return this.capturesRootDir();
  }

  /** Create .agent-eyes/.gitignore once, without clobbering user edits. */
  async ensureGitignore(): Promise<void> {
    if (this.gitignoreEnsured) {
      return;
    }
    const root = this.agentEyesRoot();
    await mkdir(root, { recursive: true });
    const file = path.join(root, ".gitignore");
    const header =
      "# generated by agent-eyes — keep heavyweight captures and secrets out of git\n" +
      "# (baselines/ is intentionally NOT ignored: commit it to share\n" +
      "# visual checkpoints with your team)\n";
    // sessions/ holds storageState tokens and vault.json holds encrypted
    // credentials — never commit either.
    const required = ["captures/", "gallery.html", "sessions/", "vault.json"];

    // Idempotent: ensure each required entry is present even when the user
    // already has a .gitignore here (the old code only wrote a brand-new file,
    // so a pre-existing one would silently miss the sessions/ secret-ignore).
    const existing = (await pathExists(file))
      ? await readFile(file, "utf8").catch(() => "")
      : "";
    const present = new Set(existing.split("\n").map((l) => l.trim()));
    const missing = required.filter((entry) => !present.has(entry));
    if (missing.length > 0) {
      const base =
        existing === ""
          ? header
          : existing.endsWith("\n")
            ? existing
            : `${existing}\n`;
      await writeFile(file, `${base}${missing.join("\n")}\n`);
    }
    this.gitignoreEnsured = true;
  }

  /**
   * Start a fresh run directory and make it the current run. Named
   * `run-<N>-<page>` (sequential counter + a slug of the URL's page) so it
   * reads at a glance, e.g. `run-1-home`, `run-3-pricing`.
   */
  async newRun(url: string): Promise<RunInfo> {
    await this.ensureGitignore();
    const root = this.capturesRootDir();
    const n = await nextRunNumber(root);
    const page = pageSlugFromUrl(url);
    let id = `run-${n}-${page}`;
    let dir = path.join(root, id);
    for (let bump = 2; await pathExists(dir); bump++) {
      id = `run-${n}-${page}-${bump}`;
      dir = path.join(root, id);
    }
    await mkdir(dir, { recursive: true });
    this.currentRun = { id, dir, usedNames: new Set(), count: 0 };
    return { id, dir };
  }

  /** Reuse the current run (consecutive interactions) or start one. */
  async ensureRun(url: string): Promise<RunInfo> {
    if (this.currentRun) {
      return { id: this.currentRun.id, dir: this.currentRun.dir };
    }
    return this.newRun(url);
  }

  /** The current run handle, for callers that just opened/joined one. */
  private requireCurrentRun(): RunHandle {
    if (!this.currentRun) {
      throw new Error("internal: no current run — call newRun/ensureRun first");
    }
    return this.currentRun;
  }

  /** Persist one encoded image into the current run and record it. */
  async saveShot(
    meta: {
      tool: PersistingTool;
      viewport: ViewportName;
      url: string;
      fragment: string | null;
      annotated: boolean;
      issueCount: number | null;
    },
    image: EncodedImage,
  ): Promise<SavedShot> {
    const run = this.requireCurrentRun();
    const now = new Date();
    const index = ++run.count;
    const nn = String(index).padStart(2, "0");
    const label = shotLabel(meta);

    // One folder per shot: NN-viewport-label/, holding the image + info.txt.
    let folderName = `${nn}-${meta.viewport}-${label}`;
    for (let bump = 2; run.usedNames.has(folderName); bump++) {
      folderName = `${nn}-${meta.viewport}-${label}-${bump}`;
    }
    run.usedNames.add(folderName);
    const shotDir = path.join(run.dir, folderName);
    await mkdir(shotDir, { recursive: true });

    const ext = extensionOf(image.mimeType);
    const file = path.join(shotDir, `${SCREENSHOT_BASENAME}.${ext}`);
    // Write-then-rename: a crash mid-write never leaves a torn image.
    const tmp = `${file}.tmp-${process.pid}`;
    await writeFile(tmp, Buffer.from(image.data, "base64"));
    await rename(tmp, file);

    const shot: SavedShot = {
      file,
      index,
      label,
      tool: meta.tool,
      viewport: meta.viewport,
      url: meta.url,
      fragment: meta.fragment,
      timestamp: now.toISOString(),
      annotated: meta.annotated,
      issueCount: meta.issueCount,
      width: image.width,
      height: image.height,
      bytes: image.bytes,
    };
    await writeShotInfo(shotDir, shot);
    await this.appendManifest(run, shot);
    return shot;
  }

  private async appendManifest(run: RunHandle, shot: SavedShot): Promise<void> {
    const manifestFile = path.join(run.dir, RUN_MANIFEST_FILENAME);
    const entries = await readManifest(run.dir);
    entries.push(shot);
    const tmp = `${manifestFile}.tmp-${process.pid}`;
    await writeFile(tmp, `${JSON.stringify(entries, null, 2)}\n`);
    await rename(tmp, manifestFile);
  }

  /**
   * (Re)build gallery.html. Aggregates every run into one contact sheet by
   * default (newest run first, so all screenshots live in one place); pass a
   * runId to scope the sheet to a single run. Returns the gallery's path.
   */
  async writeGallery(scopeRunId?: string): Promise<string> {
    const root = this.capturesRootDir();
    let shots: GalleryShot[];
    let heading: string;
    if (scopeRunId) {
      shots = (await readManifest(path.join(root, scopeRunId))).map((s) => ({
        ...s,
        runId: scopeRunId,
      }));
      heading = scopeRunId;
    } else {
      shots = await readAllShots(root);
      const runCount = new Set(shots.map((s) => s.runId)).size;
      heading = `all runs · ${runCount} run${runCount === 1 ? "" : "s"}`;
    }
    const file = path.join(this.agentEyesRoot(), GALLERY_FILENAME);
    const html = renderGalleryHtml(heading, shots, this.agentEyesRoot());
    const tmp = `${file}.tmp-${process.pid}`;
    await writeFile(tmp, html);
    await rename(tmp, file);
    return file;
  }

  /**
   * Paint red outline boxes over every finding, take a fullPage shot, save
   * it as the run's annotated render, and always remove the overlay again —
   * the persistent page must never keep our scaffolding in its DOM.
   */
  async annotateAndSave(
    page: Page,
    scan: LayoutScan,
    viewport: ViewportName,
    encoder: Encoder,
  ): Promise<SavedShot | null> {
    const selectors = collectIssueSelectors(scan);
    if (selectors.length === 0) {
      return null;
    }
    try {
      await page.evaluate(paintIssueOverlay, selectors);
      // Full page (capped): findings often sit below the viewport fold.
      const raw = await rawScreenshot(page, true);
      const image = await encoder.encode(raw.png, {
        format: MATRIX_FORMAT,
        quality: MATRIX_QUALITY,
      });
      return await this.saveShot(
        {
          tool: "layout",
          viewport,
          url: page.url(),
          fragment: null,
          annotated: true,
          issueCount: countLayoutIssues(scan),
        },
        image,
      );
    } catch (error) {
      console.error(
        `agent-eyes: overlay annotation failed (${messageOf(error)}); continuing without it`,
      );
      return null;
    } finally {
      await page
        .evaluate(() => {
          document.getElementById("__agent_eyes_overlay__")?.remove();
        })
        .catch(() => undefined);
    }
  }
}
